# Generated by Django 3.0.4 on 2020-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='point',
            field=models.IntegerField(choices=[(10, '10'), (9, '9'), (8, '8'), (7, '7'), (6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default='10'),
        ),
    ]
