# Generated by Django 3.0.4 on 2020-03-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20200331_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='point',
            new_name='rate',
        ),
    ]
