# Generated by Django 2.2.5 on 2020-04-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('recipe', '0006_auto_20200331_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default='5'),
        ),
    ]
