# Generated by Django 3.0.4 on 2020-03-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlike',
            old_name='like_recipe',
            new_name='recipe',
        ),
    ]
