# Generated by Django 3.0.4 on 2020-03-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200330_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLike',
        ),
    ]
